Add Recursion Detection middleware to all SDK requests
aws/aws-sdk-go-v2 pull request #2105
Opened 2023-04-21 04:20 UTC by wty-Bryant

Add Recursion Detection middleware to all SDK requests, which detects Lambda environment and sets its X-Ray trace ID to request header if absent to avoid recursion invocation in Lambda environment. Solves #2025

2023-04-21 12:35 UTC, aajtodd requested changes
Looks pretty good overall!

2023-04-21 12:35 UTC, aajtodd commented on aws/middleware/middleware_test.go
> +			initialLambdaFunc, hasInitialLambdaFunc := os.LookupEnv(lambdaFunc)
It's unfortunate that the testing utils that already [exist](https://github.com/aws/aws-sdk-go-v2/blob/main/internal/awstesting/util.go#L97) for this depend on `aws` package. 

I think we can simplify this by just clearing the environment and restoring it after the test such that each test gets a clean environment, [example](https://github.com/aws/aws-sdk-go-v2/blob/main/aws/middleware/user_agent_test.go#L120)

Then you won't need the additional `setEnvVar`/`recordEnvVar` functions and we guarantee tests are isolated

2023-04-21 12:35 UTC, aajtodd commented on aws/middleware/middleware_test.go
> +	const lambdaFunc = "AWS_LAMBDA_FUNCTION_NAME"
**suggestion**: You could define these as internal constants in the middleware and the test can just re-use them

e.g.

```go
// file: recursion_detection.go

const envAwsLambdaFunctionName = "AWS_LAMBDA_FUNCTION_NAME"
const envAmznTraceId = "_X_AMZN_TRACE_ID"
const amznTraceIdHeader = "X-Amzn-Trace-Id"
```

2023-04-24 15:56 UTC, lucix-aws approved these changes

2023-04-24 19:25 UTC, aajtodd approved these changes

2023-04-24 20:34 UTC, merged