Adds support for access-point and outposts for s3 / s3control client
aws/aws-sdk-go-v2 pull request #870
Opened 2020-11-02 05:54 UTC by skotambkar

[x] Adds customizations for s3 to support accesspoint and outposts accesspoint arn formats
[x] Adds customizations for s3control to support outposts accesspoint and outposts bucket arn formats

- Depends on awslabs/smithy-go#223

2020-11-05 19:55 UTC, skmcgrail requested changes

2020-11-05 19:55 UTC, skmcgrail commented on codegen/smithy-aws-go-codegen/src/main/java/software/amazon/smithy/aws/go/codegen/customization/S3UpdateEndpoint.java
> +    );
nit: formatting is inconsistent

2020-11-05 19:55 UTC, skmcgrail commented on codegen/smithy-aws-go-codegen/src/main/java/software/amazon/smithy/aws/go/codegen/customization/S3UpdateEndpoint.java
> +    }
nit: formatting

2020-11-05 19:55 UTC, skmcgrail commented on codegen/smithy-aws-go-codegen/src/main/java/software/amazon/smithy/aws/go/codegen/customization/S3UpdateEndpoint.java
> +     *  func backfillAccountID(in interface, v string) (interface{},error) {
I believe our designs did not want to generate methods on the types themselves. I would propose we generate a single `backfillAccountID` that handles the type cast and setting the value appropriately.

```go
func backfillAccountID(i interface{}, v string) error {
    switch in := i.(type) {
    case *OperationInput:
       if in.AccountId != nil {
		if !strings.EqualFold(*in.AccountId, v) {
			return fmt.Errorf("error backfilling account id")
		}
		return nil
	}
	in.AccountId = &v
	return nil
    default:
        return fmt.Errorf("unsupported operation")
    }
}
```

Similar feedback for the other member update functions.

2020-11-05 20:09 UTC, skmcgrail commented on service/internal/s3shared/arn_lookup.go
> +func (m *InitARNLookupMiddleware) ID() string {
nit: Avoid naming middleware with the name middleware in the type.

2020-11-05 20:09 UTC, skmcgrail commented on service/internal/s3shared/arn_lookup.go
> +func (m *InitARNLookupMiddleware) ID() string {
Additionally no need to have "Middleware" in the ID itself.

2020-11-12 01:18 UTC, skmcgrail requested changes

2020-11-12 01:18 UTC, skmcgrail commented on service/s3control/internal/customizations/update_endpoint.go
> +	}, (&processARNResource{}).ID(), middleware.Before)
nit: `(*processARNResource)(nil).ID()`

2020-11-12 01:18 UTC, skmcgrail commented on service/s3control/internal/customizations/update_endpoint_test.go
> +		// },
Should these be re-enabled?

2020-11-12 02:04 UTC, skotambkar commented on codegen/smithy-aws-go-codegen/src/main/java/software/amazon/smithy/aws/go/codegen/customization/S3UpdateEndpoint.java
> +            writer.openBlock("func getBucketFromInput(input interface{}) (*string, bool) {", "}", () -> {
The old switch pattern is being used in other services too, I want to decouple and view it as a separate change which also addresses other service customizations that use old pattern.

2020-11-12 02:07 UTC, skotambkar commented on service/s3control/api_client.go
>  }
This is limited to two operation cases. Separating them doesn't really provide much performance benefit, but can do it for consistency

2020-11-12 02:14 UTC, skotambkar commented on service/s3control/api_op_CreateJob.go
> +}
That's the downside of accessor pattern. Not generating these would require code generation to have additional checks. But my concern was more towards customization always having to check for nil for accessors, it seemed more error prone when I wrote this.

2020-11-12 02:24 UTC, skotambkar commented on service/s3control/internal/customizations/backfill_input.go
> +	}
For s3control we mutate the input further down the middleware stack if accesspoint/outpost arn. But yeah I agree visibility is lost if paired only with this middleware. (Idea was to do it here, as this is one of the most initial middlewares to be executed).

May be we should have a key on context for this too if we want to conditionally copy. Without the context key, we would end up copying an input multiple times in different stack steps.

2020-11-12 18:04 UTC, skotambkar commented on service/s3control/internal/customizations/process_arn_resource.go
> +		}
Fips is not supported for outposts. The `UseFIPS and !UseARNRegion` combination checks if a request is configured for a fips region and  use arn region is not set. In this case, SDK will attempt to use the fips region, which is not valid for outposts.

2020-11-12 21:40 UTC, skotambkar commented on codegen/smithy-aws-go-codegen/src/main/java/software/amazon/smithy/aws/go/codegen/EndpointGenerator.java
> +    private static class ResolveConfigField extends ConfigField {
This is just IntelliJ's Java formatter, which reshuffled few things as per its rules.  Not sure what ordering it follows

2020-11-13 23:26 UTC, skmcgrail requested changes
Just a couple minor comments otherwise looks good

2020-11-13 23:26 UTC, skmcgrail commented on service/internal/s3shared/endpoint_error.go
> +
We don't want to expose this concept of a Code on non service API errors. This should only be `Error` and `Unwrap` and optionally any sort of "getter" type accessors if the error is wrapping and wanting to provide additional context.

2020-11-13 23:26 UTC, skmcgrail commented on service/s3control/internal/customizations/process_arn_resource.go
> +		}
nit: You could move the clone action to immediately before the switch statement. At worst if the user provided an invalid ARN resource we would have made an unnecessary copy. But it results in not needing to duplicate this between resource types.

2020-11-13 23:27 UTC, skmcgrail commented on service/s3control/internal/customizations/process_arn_resource.go
> +		}
Ah ok so `UseARNRegion` and `UseFIPS` act slightly differently for outposts ARNs. Cause for accesspoints I believe the logic is different in that a FIPS reuqest with UseARNRegion is not allowed.

2020-11-14 00:15 UTC, skotambkar commented on service/s3control/internal/customizations/process_arn_resource.go
> +		}
yeah outposts has a different behavior and doesn't support fips at all.

2020-11-16 21:20 UTC, jasdel commented on service/s3/internal/customizations/update_endpoint.go
> +}
Should `SupportsAccelerate` be a member of the `UpdateEndpointOptions`? Seems out of place in the Accessor's group.

2020-11-17 18:08 UTC, skmcgrail approved these changes

2020-11-17 18:35 UTC, merged