Add Middleware Developer Guide
aws/aws-sdk-go-v2 pull request #954
Opened 2020-12-08 04:29 UTC by skmcgrail

Adds developer guide content describing how users can use the middleware stack to extend the SDK request pipeline.

Closes: https://github.com/aws/aws-sdk-go-v2/issues/904

2020-12-08 20:53 UTC, Doug-AWS requested changes

2020-12-08 20:53 UTC, Doug-AWS commented on content/en/docs/middleware.md
> +Ypu attach step middleware by using a step's `Insert` or `Add` methods. You use `Add` to attach a middleware to the
Ypu -> You

2020-12-08 20:53 UTC, Doug-AWS commented on content/en/docs/middleware.md
> +The following examples shows how you can write a custom middleware to populate Bucket member of the
show
the Bucket

2020-12-08 20:53 UTC, Doug-AWS commented on content/en/docs/middleware.md
> +This middleware is meant to be a a full end-to-end example of how to construct and attach step middleware to the stack.
meant to be a a -> a

2020-12-08 20:53 UTC, Doug-AWS commented on content/en/docs/middleware.md
> +This example is not official guidance on how you should structure API service input, and is only meant to show you
This statement is not necessary. No example implies official guidance.

2020-12-08 20:53 UTC, Doug-AWS commented on content/en/docs/middleware.md
> +	// Alternatively if an error has occurred you may return prematurely to prevent further execution.
If an error occurs, you can return to prevent further execution.

2020-12-08 20:53 UTC, Doug-AWS commented on content/en/docs/middleware.md
> +[aws.Config]({{< apiref "aws#Config" >}}) type. For example, to attach the `defaultBucket` middleware to every
The following example attaches

2020-12-08 20:53 UTC, Doug-AWS commented on content/en/docs/middleware.md
> +member using the variadic argument list for an operation. For example, to attach the `defaultBucket` middleware to only
The following example attaches

2020-12-08 20:53 UTC, Doug-AWS commented on content/en/docs/middleware.md
> +[middleware.Metadata]({{< apiref smithy="middleware#Metadata" >}}). Each middleware step returns an output type,
class?

2020-12-09 18:54 UTC, skmcgrail commented on content/en/docs/middleware.md
> +You can customize {{% alias sdk-go %}} client requests by registering one or more middleware to a service operation's
this carries onward to line 14 with the word `stack` which is linked to an API reference guide type.

2020-12-10 19:45 UTC, merged